import { transformerTwoslash } from "@shikijs/vitepress-twoslash";
import { defineConfig } from "vitepress";
import llmstxt, { copyOrDownloadAsMarkdownButtons } from "vitepress-plugin-llms";
// Generated by scripts/generate-api-sidebar.mjs during docs:api
// Run `npm run docs:api` if these imports fail
import sidebarCore from "./sidebar-core.json" with { type: "json" };
import sidebarSchemaExport from "./sidebar-schema-export.json" with { type: "json" };
import sidebarNestjs from "./sidebar-nestjs.json" with { type: "json" };

export default defineConfig({
  title: "ConfigBound",
  description: "Type-safe configuration management for TypeScript.",
  base: "/ConfigBound/",
  cleanUrls: true,
  vite: {
    plugins: [llmstxt({})],
  },
  markdown: {
    codeTransformers: [transformerTwoslash({
      processHoverDocs(docs: string) {
        return docs.replace(
          /\s*\{@link\s+([\s\S]*?)\}\s*/g,
          (_, content) => ` ${content.replace(/\s+/g, " ").trim()} `,
        ).trim();
      },
    })],
    config(md) {
      md.use(copyOrDownloadAsMarkdownButtons);
    },
  },
  themeConfig: {
    nav: [
      { text: "Tutorials", link: "/tutorials/" },
      { text: "How-to Guides", link: "/how-to/" },
      { text: "Reference", link: "/reference/" },
      { text: "Explanation", link: "/explanation/" },
    ],
    sidebar: {
      "/tutorials/": [
        {
          text: "Tutorials",
          items: [
            { text: "Overview", link: "/tutorials/" },
            { text: "Getting Started", link: "/tutorials/getting-started" },
          ],
        },
      ],
      "/how-to/": [
        {
          text: "How-to Guides",
          items: [{ text: "Overview", link: "/how-to/" }],
        },
        {
          text: "Binds",
          items: [
            { text: "Environment Variable", link: "/how-to/env-var-bind" },
            { text: "File", link: "/how-to/file-bind" },
            { text: "Static", link: "/how-to/static-bind" },
            { text: "Create a custom bind", link: "/how-to/custom-bind" }
          ],
        },
        {
          text: "Integrations",
          items: [
            { text: "Use with NestJS", link: "/how-to/nestjs" }
          ],
        },
        {
          text: "Schema",
          items: [{ text: "Export your configuration schema", link: "/how-to/schema-export" }],
        },
      ],
      "/reference/": [
        {
          text: "Reference",
          items: [
            { text: "Overview", link: "/reference/" },
          ],
        },
        {
          text: "API Packages",
          items: [
            { text: "@config-bound/config-bound", link: "/reference/api/@config-bound.config-bound" },
            { text: "@config-bound/schema-export", link: "/reference/api/@config-bound.schema-export" },
            { text: "@config-bound/nestjs", link: "/reference/api/@config-bound.nestjs" },
          ],
        },
        {
          text: "CLI",
          items: [
            { text: "Overview", link: "/reference/cli/" },
          ],
        },
      ],
      "/reference/api/@config-bound.config-bound": [
        {
          text: "",
          items: [
            { text: "All packages", link: "/reference/" },
          ],
        },
        ...sidebarCore,
      ],
      "/reference/api/@config-bound.schema-export": [
        {
          text: "",
          items: [
            { text: "All packages", link: "/reference/" },
          ],
        },
        ...sidebarSchemaExport,
      ],
      "/reference/api/@config-bound.nestjs": [
        {
          text: "",
          items: [
            { text: "All packages", link: "/reference/" },
          ],
        },
        ...sidebarNestjs,
      ],
      "/reference/cli/": [
        {
          text: "",
          items: [
            { text: "All packages", link: "/reference/" },
          ],
        },
        {
          text: "CLI",
          items: [
            { text: "Overview", link: "/reference/cli/" },
            { text: "configbound list", link: "/reference/cli/list" },
            { text: "configbound export", link: "/reference/cli/export" },
            { text: "configbound generate bind", link: "/reference/cli/generate-bind" },
          ],
        },
      ],
      "/explanation/": [
        {
          text: "Explanation",
          items: [
            { text: "Overview", link: "/explanation/" },
            { text: "Anatomy of ConfigBound", link: "/explanation/anatomy-of-configbound" },
            { text: "Docs as Code", link: "/explanation/docs-as-code" },
            { text: "Schema as the Source of Truth", link: "/explanation/schema-source-of-truth" },
          ],
        },
      ],
    },
    search: {
      provider: "local",
    },
    socialLinks: [{ icon: "github", link: "https://github.com/notr-ai/ConfigBound" }],
    footer: {
      message: "",
      copyright: "Copyright © ConfigBound",
    },
  },
});
